### ISSUE TITLE
unable to run the code "python page_extractor.py -i 'input/page.jpg' "

### ISSUE THREAD

**Issue by SiddharthaShandilya** [Shakleen/Python-Document-Detector#19]
i have created a separate conda environment and installed all the required dependencies.

below is the error shown
-------------------------------------------------------------------------
Traceback (most recent call last):
  File "page_extractor.py", line 145, in <module>
    extracted = page_extractor(args.input_image)
  File "page_extractor.py", line 25, in __call__
    self._processed = preprocessor(self._processed)
  File "D:\projects_prototype\Python-Document-Detector\processors.py", line 62, in __call__
    if image.shape[0] <= self._height: return image
AttributeError: 'NoneType' object has no attribute 'shape'
-------------------------------------------------------------------------

**Comment by Shakleen** [comment]
Looks like it's failing at the pre-process stage.  Could you confirm whether the image path is provided correctly and the image is being loaded?

**Comment by SiddharthaShandilya** [comment]
yeah the problem was with image path, it started working when I removed the single quotes from the image location in the  command
  " python page_extractor.py -i input/page.jpg "
